###recuperar los clientes
GET http://localhost:3001/client

###recuperar cliente
GET http://localhost:3001/client/1

###recuperar los productos
GET http://localhost:3001/product

###recuperar todas las facturas
GET http://localhost:3001/invoice

###recuperar facturas por cliente
GET http://localhost:3001/invoice/2

###crear una factura

POST http://localhost:3001/invoice
content-type: application/json

{
    "client": 2,
    "date": "2024-04-05",
    "subtotal": 200,
    "discount": 0,
    "total": 400
}

###recuperar relación de clientes por factura
GET http://localhost:3001/invoice-product/2

###crear nuevo cliente a factura en especifico

POST http://localhost:3001/invoice-product
content-type: application/json

{
    "invoice": 4,
    "product": 344,
    "quantity": 2
}
###crear nuevo usuario

POST http://localhost:3001/auth/register
content-type: application/json

{
"email": "dave@virtues.com",
"password": "Virtues23Dave"
}
###login

POST http://localhost:3001/auth/sign-in
content-type: application/json

{
"username": "dave@virtues.com",
"password": "Virtues23Dave"
}